---
apiVersion: v2

name: auth
description: PowerDNS (PDNS) Authoritative Server
type: application

home: https://github.com/muhlba91/pdns-container
sources:
  - https://github.com/muhlba91/pdns-container
keywords:
  - powerdns
  - pdns
  - pdns-auth

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel.muehlbachler@niftyside.io

# NOTE: this value is updated by the release process
appVersion: "@sha256:073d97ee828b9e931e19328695e3fcd668a76e868c068887c34754ed3b356eaf"
# NOTE: this value is updated by the release process
version: 1.0.5
